package com.iny.side.assignment.mock;

import com.iny.side.assignment.domain.entity.Assignment;
import com.iny.side.assignment.domain.repository.AssignmentRepository;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Slice;
import org.springframework.data.domain.SliceImpl;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeAssignmentRepository implements AssignmentRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Assignment> data = new ArrayList<>();

    public Assignment save(Assignment assignment) {
        if (assignment.getId() == null || assignment.getId() == 0) {
            Assignment savedAssignment = Assignment.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .title(assignment.getTitle())
                    .personaName(assignment.getPersonaName())
                    .personaAge(assignment.getPersonaAge())
                    .personaGender(assignment.getPersonaGender())
                    .personaSymptom(assignment.getPersonaSymptom())
                    .personaHistory(assignment.getPersonaHistory())
                    .personaPersonality(assignment.getPersonaPersonality())
                    .personaDisease(assignment.getPersonaDisease())
                    .objective(assignment.getObjective())
                    .maxTurns(assignment.getMaxTurns())
                    .dueDate(assignment.getDueDate())
                    .course(assignment.getCourse())
                    .build();

            data.add(savedAssignment);
            return savedAssignment;
        }
        data.removeIf(item -> Objects.equals(item.getId(), assignment.getId()));
        data.add(assignment);
        return assignment;
    }

    @Override
    public Optional<Assignment> findByAssignmentId(Long assignmentId) {
        return data.stream()
                .filter(item -> Objects.equals(item.getId(), assignmentId))
                .findFirst();
    }

    @Override
    public void delete(Assignment assignment) {
        data.remove(assignment);
    }

    @Override
    public List<Assignment> findAllByCourseId(Long courseId) {
        return data.stream()
                .filter(assignment -> assignment.getCourse() != null &&
                        Objects.equals(assignment.getCourse().getId(), courseId))
                .toList();
    }

    @Override
    public Slice<Assignment> findAllByCourseId(Long courseId, Pageable pageable) {
        List<Assignment> filtered = data.stream()
                .filter(assignment -> assignment.getCourse() != null &&
                        Objects.equals(assignment.getCourse().getId(), courseId))
                .toList();

        int start = (int) pageable.getOffset();
        int end = Math.min(start + pageable.getPageSize(), filtered.size());

        List<Assignment> content = start < filtered.size() ? filtered.subList(start, end) : new ArrayList<>();
        boolean hasNext = end < filtered.size();

        return new SliceImpl<>(content, pageable, hasNext);
    }
}
